version: "2"
services:
  nginx:
    image: nginx:latest
    container_name: check_nginx
    ports:
      - "80:80"
    volumes:
      - ./conf/site_nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www/public_html:/www/public_html

  php-cli:
    build: ./conf/php
    container_name: check_php
    volumes:
      - ./www:/www
